# https://www.appveyor.com/docs/appveyor-yml

version: "{build}"
init:
  - git config --global core.autocrlf false
shallow_clone: true
environment:
  matrix:
    - nodejs_version: "4"
    - nodejs_version: "6"
    - nodejs_version: "7"
cache:
 - "%LOCALAPPDATA%\\Yarn"
skip_tags: true
build: off
install:
  - ps: Install-Product node $env:nodejs_version
  - yarn
before_test:
  - ./node_modules/.bin/lerna bootstrap
test_script:
  - yarn start ci
